// Static copy and structured data for Bob Photography.
// Supports editorial Awwwards-quality presentation with rich metadata for each photograph.

window.SITE_COPY = {
  brand: {
    name: "Bob",
    tagline: "The Friendly Neighborhood Photographer",
    location: "Minneapolis · St. Paul · Twin Cities Metro",
    coordinates: "44.9778° N, 93.2650° W",
    statusBadge: "Available for 2026 Sessions",
  },

  nav: {
    links: [
      { label: "Portfolio", href: "#work" },
      { label: "Services", href: "#services" },
      { label: "About", href: "#about" },
      { label: "Process", href: "#process" },
      { label: "FAQ", href: "#faq" },
    ],
    cta: "Book a Shoot",
  },

  hero: {
    tag: "Twin Cities Photodocumentary & Portraits",
    eyebrow: "Portraits · Families · Sports · Live Events",
    headlineMain: "Unscripted Moments.",
    headlineAccent: "Frozen Sharp.",
    sub: "Natural light, genuine laughter, and split-second athletic action across the Minneapolis & St. Paul metro. No stiff poses. No hidden fees. Just real life captured honestly.",
    primaryCta: "Book a Session",
    secondaryCta: "Explore Portfolio ↓",
    stats: [
      { num: "48hr", label: "Sneak Peek Delivery" },
      { num: "100%", label: "Unscripted Real Moments" },
      { num: "Twin Cities", label: "Metro & Beyond" },
    ],
  },

  portfolio: {
    eyebrow: "Curated Portfolio",
    heading: "Four Disciplines. One Uncompromising Eye.",
    sub: "Every frame captures an unrepeatable second — authentic smiles, dynamic athletic motion, and the electricity of live gatherings.",
    tabs: ["All", "Portraits", "Families", "Sports", "Events"],
    items: [
      // Portraits
      {
        id: "port-1",
        category: "Portraits",
        title: "Golden Hour Character",
        location: "Minneapolis, MN",
        meta: "85mm · f/1.4 · 1/800s",
        src: "images/gallery/port-1.webp",
        aspect: "vertical",
        caption: "Natural sunlight highlighting genuine warmth and character in an unposed outdoor setting.",
      },
      {
        id: "port-2",
        category: "Portraits",
        title: "Reflective Gaze",
        location: "St. Paul, MN",
        meta: "50mm · f/1.8 · 1/500s",
        src: "images/gallery/port-2.webp",
        aspect: "vertical",
        caption: "Intimate portrait focusing on expression and quiet strength with soft depth of field.",
      },
      {
        id: "port-3",
        category: "Portraits",
        title: "Joy in Motion",
        location: "Minnehaha Falls, MN",
        meta: "35mm · f/2.0 · 1/1000s",
        src: "images/gallery/port-3.webp",
        aspect: "vertical",
        caption: "Catching genuine laughter in the middle of conversation.",
      },
      {
        id: "port-4b",
        category: "Portraits",
        title: "Studio Contour",
        location: "North Loop Studio",
        meta: "85mm · f/2.8 · 1/250s",
        src: "images/gallery/port-4b.webp",
        aspect: "vertical",
        caption: "Controlled studio illumination sculpting facial contours and authentic confidence.",
      },
      {
        id: "port-5",
        category: "Portraits",
        title: "Ambient Horizon",
        location: "Chain of Lakes, MN",
        meta: "50mm · f/1.4 · 1/640s",
        src: "images/gallery/port-5.webp",
        aspect: "vertical",
        caption: "Environmental portrait blending the subject naturally into the surrounding landscape.",
      },
      {
        id: "port-6",
        category: "Portraits",
        title: "Expressive Candid",
        location: "Minneapolis, MN",
        meta: "85mm · f/1.8 · 1/400s",
        src: "images/gallery/port-6.webp",
        aspect: "vertical",
        caption: "The half-second between expressions where personality shines through.",
      },

      // Families
      {
        id: "pfam-1",
        category: "Families",
        title: "Lakeside Connection",
        location: "Lake Harriet, MN",
        meta: "35mm · f/2.2 · 1/1250s",
        src: "images/gallery/pfam-1.webp",
        aspect: "horizontal",
        caption: "Energetic family stroll along the shoreline with authentic spontaneous interactions.",
      },
      {
        id: "pfam-2",
        category: "Families",
        title: "Shared Laughter",
        location: "St. Anthony Main",
        meta: "50mm · f/2.0 · 1/800s",
        src: "images/gallery/pfam-2.jpg",
        aspect: "vertical",
        caption: "Unrehearsed moment of pure familial warmth.",
      },
      {
        id: "pfam-3",
        category: "Families",
        title: "Generational Warmth",
        location: "Edina, MN",
        meta: "85mm · f/2.5 · 1/500s",
        src: "images/gallery/pfam-3.jpg",
        aspect: "vertical",
        caption: "Documenting multi-generational connection in a relaxed backyard setting.",
      },
      {
        id: "pfam-4",
        category: "Families",
        title: "Golden Meadow",
        location: "Theodore Wirth Park",
        meta: "35mm · f/1.8 · 1/1600s",
        src: "images/gallery/pfam-4.jpg",
        aspect: "horizontal",
        caption: "Children exploring the open grass under evening sunlight.",
      },
      {
        id: "pfam-5",
        category: "Families",
        title: "Autumn Breeze",
        location: "Highland Park, St. Paul",
        meta: "50mm · f/2.8 · 1/640s",
        src: "images/gallery/pfam-5.jpg",
        aspect: "vertical",
        caption: "Candid smiles amidst vibrant seasonal foliage.",
      },
      {
        id: "pfam-6",
        category: "Families",
        title: "The Whole Crew",
        location: "Lake of the Isles, MN",
        meta: "28mm · f/4.0 · 1/1000s",
        src: "images/gallery/pfam-6.webp",
        aspect: "horizontal",
        caption: "Wide group composition capturing everybody in their element.",
      },

      // Sports
      {
        id: "sport-1",
        category: "Sports",
        title: "Mid-Air Flight",
        location: "Twin Cities Fieldhouse",
        meta: "70-200mm · f/2.8 · 1/2500s",
        src: "images/gallery/sport-1.webp",
        aspect: "horizontal",
        caption: "Peak athletic extension frozen at the apex of the jump.",
      },
      {
        id: "sport-2",
        category: "Sports",
        title: "Decisive Strike",
        location: "Minneapolis Ice Arena",
        meta: "70-200mm · f/2.8 · 1/2000s",
        src: "images/gallery/sport-2.webp",
        aspect: "horizontal",
        caption: "Puck impact and ice spray captured in razor-sharp focus.",
      },
      {
        id: "sport-3",
        category: "Sports",
        title: "Fast Break Drive",
        location: "Hopkins Gym, MN",
        meta: "50mm · f/1.8 · 1/1600s",
        src: "images/gallery/sport-3.webp",
        aspect: "vertical",
        caption: "High-intensity court action documenting speed and defensive determination.",
      },
      {
        id: "sport-4",
        category: "Sports",
        title: "Diamond Focus",
        location: "Midway Stadium, St. Paul",
        meta: "300mm · f/4.0 · 1/3200s",
        src: "images/gallery/sport-4.jpg",
        aspect: "horizontal",
        caption: "The batter's eye locked on the incoming pitch.",
      },
      {
        id: "sport-5",
        category: "Sports",
        title: "Turf Battle",
        location: "U of M Sports Complex",
        meta: "70-200mm · f/2.8 · 1/2000s",
        src: "images/gallery/sport-5.jpg",
        aspect: "horizontal",
        caption: "Full-speed clash at midfield with crisp detail on grass and jersey texture.",
      },
      {
        id: "sport-6",
        category: "Sports",
        title: "Victory Eruption",
        location: "Twin Cities Arena",
        meta: "24-70mm · f/2.8 · 1/1250s",
        src: "images/gallery/sport-6.webp",
        aspect: "horizontal",
        caption: "Post-game celebration capturing pure relief and team euphoria.",
      },

      // Events
      {
        id: "event-1",
        category: "Events",
        title: "Stage Spotlight",
        location: "First Avenue, Minneapolis",
        meta: "24mm · f/1.8 · 1/500s",
        src: "images/gallery/event-1.webp",
        aspect: "horizontal",
        caption: "Atmospheric stage lighting illuminating the lead performer in full flow.",
      },
      {
        id: "event-2",
        category: "Events",
        title: "Crowd Surge",
        location: "Armory Minneapolis",
        meta: "35mm · f/2.0 · 1/400s",
        src: "images/gallery/event-2.webp",
        aspect: "horizontal",
        caption: "Electrifying crowd reaction as the music peaks.",
      },
      {
        id: "event-3",
        category: "Events",
        title: "Intimate Acoustic",
        location: "Cedar Cultural Center",
        meta: "85mm · f/1.4 · 1/320s",
        src: "images/gallery/event-3.jpg",
        aspect: "vertical",
        caption: "Subtle venue lighting highlighting acoustic guitar fingering and vocal passion.",
      },
      {
        id: "event-4",
        category: "Events",
        title: "Gala Keynote",
        location: "Guthrie Theater Lounge",
        meta: "50mm · f/2.0 · 1/250s",
        src: "images/gallery/event-4.jpg",
        aspect: "horizontal",
        caption: "Capturing speaking cadence and engaging audience attentiveness.",
      },
      {
        id: "event-5",
        category: "Events",
        title: "Evening Spark",
        location: "Nicollet Island Pavilion",
        meta: "35mm · f/1.4 · 1/200s",
        src: "images/gallery/event-5.jpg",
        aspect: "horizontal",
        caption: "Ambient candle and string lights setting a romantic celebration vibe.",
      },
      {
        id: "event-6",
        category: "Events",
        title: "Full Room Harmony",
        location: "Orchestra Hall, MN",
        meta: "16-35mm · f/2.8 · 1/160s",
        src: "images/gallery/event-6.webp",
        aspect: "horizontal",
        caption: "Architectural wide shot taking in the whole spectacle from floor to balcony.",
      },
    ],
  },

  services: {
    eyebrow: "Disciplines & Offerings",
    heading: "Tailored for Real Moments, Not Stiff Poses.",
    sub: "Whether you need a compelling individual portrait, a joyful family session, or high-octane sports coverage, every package includes upfront transparent pricing, quick sneak peeks, and high-res digital files.",
    items: [
      {
        num: "01",
        id: "portraits",
        title: "Individual Portraits",
        tagline: "The real you, without the awkwardness.",
        body: "Great portraits happen when you forget the camera exists. We'll talk, joke, wander an inspiring location, and capture the natural expressions that define who you are.",
        features: ["60–90 min session", "20+ edited high-res images", "Multiple outfit & look changes", "Print rights included"],
        highlight: "Perfect for creatives, professionals, seniors, and personal branding.",
      },
      {
        num: "02",
        id: "families",
        title: "Family Sessions",
        tagline: "Organized chaos, beautifully documented.",
        body: "Kids running around, spontaneous tickle fights, real laughter. I don't force everyone to freeze and say cheese; I document your family's real dynamic as it naturally unfolds.",
        features: ["60 min session", "40+ edited high-res images", "Outdoor park or in-home lifestyle", "Fast 48h preview gallery"],
        highlight: "Pets are always welcomed and encouraged.",
      },
      {
        num: "03",
        id: "sports",
        title: "Sports & Action",
        tagline: "Peak athletic intensity, frozen sharp.",
        body: "From youth leagues and high school championships to club tournaments, I track the rhythm of the game so the lens is already waiting where the decisive play occurs.",
        features: ["Full game or meet coverage", "Individual athlete action focus", "High-speed burst capture", "Team packages available"],
        highlight: "Guaranteeing at least one standout heroic action frame for every player.",
      },
      {
        num: "04",
        id: "events",
        title: "Live Events & Gatherings",
        tagline: "The complete story from doors opening to final toast.",
        body: "Unobtrusive documentary coverage that captures both major milestones and subtle in-between interactions without interrupting the natural flow of your event.",
        features: ["Hourly & full-day coverage", "Comprehensive storytelling arc", "Quick turnaround for PR/social", "High-res & web-optimized downloads"],
        highlight: "Concerts, community festivals, corporate gatherings, and milestone parties.",
      },
    ],
  },

  about: {
    eyebrow: "Behind the Lens",
    heading: "Nosy about people, obsessed with split-second timing.",
    body: [
      "I fell in love with photography while documenting the wild, nonstop adventures of my own family and three kids across sports, school, music, and everyday life.",
      "When my kids got tired of me pointing a lens at them, I began helping friends, neighbors, and local teams document their milestones. That passion grew into Bob Photography.",
      "My technical reflex allows me to adapt immediately to changing lighting and fast-moving action so that on shoot day, I can focus entirely on being present and making people feel relaxed.",
    ],
    badges: [
      { label: "Location", value: "Minneapolis, MN" },
      { label: "Experience", value: "10+ Years Documenting Real Life" },
      { label: "Specialty", value: "Portraits, Families, Sports, Events" },
      { label: "Travel", value: "All Across Twin Cities & Greater MN" },
    ],
    quotes: "“The best photograph is the one where you feel something real, not the one where you posed the hardest.”",
  },

  process: {
    eyebrow: "How It Works",
    heading: "Effortless from First Message to Final Gallery.",
    steps: [
      {
        step: "01",
        title: "Connect & Plan",
        desc: "We chat via email, phone, or over coffee. We align on your vision, location, timing, and confirm clear, all-inclusive pricing with zero surprises.",
      },
      {
        step: "02",
        title: "The Shoot Day",
        desc: "I arrive early with top-tier gear and a calm, friendly vibe. You just be yourselves; I handle the lighting, composition, and timing.",
      },
      {
        step: "03",
        title: "Fast Delivery",
        desc: "Get sneak peek frames within 48 hours to share right away. Your private, high-resolution digital gallery arrives shortly after with full personal print rights.",
      },
    ],
  },

  faq: {
    eyebrow: "Frequently Asked Questions",
    heading: "Everything You Need to Know",
    items: [
      {
        q: "What areas of the Twin Cities do you serve?",
        a: "I shoot across Minneapolis, St. Paul, and surrounding suburbs (Edina, Minnetonka, Bloomington, Woodbury, Maple Grove, and beyond). Willing to travel further across Minnesota upon request!",
      },
      {
        q: "How fast will I receive my photos?",
        a: "You'll receive a curated set of sneak peeks within 48 hours. The complete, fully color-graded high-resolution gallery is delivered within 7 to 10 days.",
      },
      {
        q: "What should we wear for our portrait or family session?",
        a: "Wear what makes you feel comfortable and confident! Complementary neutral tones, earthy palettes, and comfortable layers look fantastic on camera. Avoid oversized logos or distracting patterns.",
      },
      {
        q: "Do I get rights to print and share my photos?",
        a: "Yes! Every session includes full personal print and sharing rights with high-resolution digital downloads directly from your private online gallery.",
      },
    ],
  },

  contact: {
    eyebrow: "Inquiry & Booking Studio",
    heading: "Let's Create Something Memorable.",
    sub: "Tell me about your idea, target date, and what you're hoping to capture. I'll get back to you within 24 hours with availability and simple pricing.",
    shootTypes: [
      { id: "Portraits", label: "Portraits", desc: "Individual, creative, senior, or personal branding" },
      { id: "Family", label: "Family Session", desc: "Candid moments with kids, couples, or extended family" },
      { id: "Sports", label: "Sports & Action", desc: "Team games, athletic portraits, or tournament coverage" },
      { id: "Events", label: "Live Event", desc: "Gatherings, performances, celebrations, or parties" },
      { id: "Other", label: "Other / Custom", desc: "Special projects, travel sessions, or unique requests" },
    ],
    directEmail: "rburmaster@hotmail.com",
    submitButton: "Send Booking Request",
    submitting: "Transmitting Request…",
    successHeading: "Message Received!",
    successMessage: "Thanks for reaching out! Bob has received your inquiry and will respond within 24 hours with ideas and availability.",
  },

  footer: {
    copyright: "© 2026 Bob Photography. All rights reserved.",
    locationBadge: "Minneapolis, Minnesota · Twin Cities Metro",
    note: "Crafted for real moments, authentic connection, and peak action.",
  },
};

